### ISSUE TITLE
Unable to Launch GroovyLab: Spontaneously Exits without Output

### ISSUE THREAD

**Issue by ssadedin** [sterglee/GroovyLab#3]
Not sure if I'm missing something, but I tried building using Gradle and JDK9:

```
gradle clean fatJar
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava 
/Volumes/Space2/tools/GroovyLab/GroovyLab-Src/com/jmatio/io/MatFileReader.java:159: warning: [dep-ann] deprecated item is not annotated with @Deprecated
    public ArrayList<MLArray> getData()
                              ^
/Volumes/Space2/tools/GroovyLab/GroovyLab-Src/groovySci/math/array/DoubleArray.java:524: warning: [dep-ann] deprecated item is not annotated with @Deprecated
public static double[][] one(int m, int n) {
                         ^
/Volumes/Space2/tools/GroovyLab/GroovyLab-Src/groovySci/math/array/DoubleArray.java:540: warning: [dep-ann] deprecated item is not annotated with @Deprecated
public static double[][] one(int m, int n, double c) {
                         ^
/Volumes/Space2/tools/GroovyLab/GroovyLab-Src/groovySci/math/array/DoubleArray.java:550: warning: [dep-ann] deprecated item is not annotated with @Deprecated
public static double[] one(int m) {
                       ^
/Volumes/Space2/tools/GroovyLab/GroovyLab-Src/groovySci/math/array/DoubleArray.java:561: warning: [dep-ann] deprecated item is not annotated with @Deprecated
        public static double[] one(int m, double c) {
                               ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 warnings


BUILD SUCCESSFUL in 3m 36s
```

But then running using either the provided scripts or executing the fat jar itself just pauses for a few seconds, temporarily shows a GroovyLab application menu, and exits.

Application menu (OSX):

![image](https://user-images.githubusercontent.com/138868/60404016-acc73d80-9be7-11e9-8c00-3858b4d3aa78.png)

Command execution:

```
$ ./MacOSRunGroovyLabJDK9.sh 
$ 
```
Any idea what's going wrong or how to get some log output to give a hint of what's happening?

**Comment by sterglee** [comment]
I tried the same command, and on Linux the produced GroovyLab-all.jar 
file runs well

with the Linux64GroovyLabDL4j.sh script.


I used Java 12.

**Comment by sterglee** [comment]
It could be because you create the fatJar, i.e. GroovyLab-all.jar is created, that contains the DeepLearning4j libraries, that are large and use native code.

Why you don't use
gradle jar

to create the basic GroovyLab.jar file?

**Comment by sterglee** [comment]
Finally, I solved the problem, 
it was due to some native libs, that worked well on Linux (which I used),
but failed on Mac and Windows.
The important native libs from the OpenBLAS project work well on all platforms.

Now, GroovyLab should load and work properly.

Please, notice me, if any other problems.
