### ISSUE TITLE
which .zip to dowload for installation?

### ISSUE THREAD

**Issue by ghost** [sterglee/GroovyLab#4]
This page https://github.com/sterglee/GroovyLab/blob/master/readme.md 
 says "Step 1 Download and unzip the .zip download." 
But where to find the .zip? 
here https://sourceforge.net/projects/groovylab/files/ ?

**Comment by papdim** [comment]
The zip at the Download option of the Github page, is named GroovyLab-master.zip

Installation is very simple, you unzip the GroovyLab-master.zip and run the 
./Linux64GroovyLab.sh
script

**Comment by ghost** [comment]
Sorry, but where exactly is such a download option?
 I can't find anywhere GroovyLab-master.zip , I browsed many folders in https://github.com/sterglee/GroovyLab

**Comment by papdim** [comment]
At the main github page:

https://github.com/sterglee/GroovyLab

the Code tab has the Download ZIP option.

**Comment by ghost** [comment]
I found it finally: had to click not just on Code tab, but also Code button, where saw "download zip".
Thank you
